import 'dart:async';

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

import '../settings/app_settings.dart';
import 'audio_service.dart';

/// flame_audio-backed [AudioService]. Kept in its own file so tests can depend on
/// the [AudioService] seam (and [NoopAudioService]) without loading audioplayers.
///
/// The placeholder WAV set lives under `assets/audio/` (flame_audio's default
/// cache prefix), generated by `tool/gen_placeholder_audio.dart`.
class FlameAudioService implements AudioService {
  FlameAudioService();

  static const List<String> _clips = <String>[
    'ui_tap.wav',
    'note_1.wav',
    'note_2.wav',
    'note_3.wav',
    'note_4.wav',
    'note_5.wav',
    'correct.wav',
    'target.wav',
    'invalid.wav',
    'fever.wav',
  ];

  double _sfxVolume = AppSettings.defaults.sfxVolume;

  @override
  Future<void> preload() async {
    try {
      await FlameAudio.audioCache.loadAll(_clips);
    } on Object catch (e) {
      // Missing/failed audio must never block gameplay (asset rule).
      debugPrint('[audio] preload failed: $e');
    }
  }

  @override
  void applySettings(AppSettings settings) {
    _sfxVolume = settings.sfxVolume;
  }

  @override
  void play(Sfx sfx) {
    if (_sfxVolume <= 0) {
      return;
    }
    _fire(_fileFor(sfx));
  }

  @override
  void playPathNote(int selectionLength) {
    if (_sfxVolume <= 0) {
      return;
    }
    final int step = selectionLength.clamp(1, 5);
    _fire('note_$step.wav');
  }

  void _fire(String file) {
    // Fire-and-forget; a failed effect never propagates into gameplay.
    unawaited(
      FlameAudio.play(file, volume: _sfxVolume).then<void>(
        (_) {},
        onError: (Object e) => debugPrint('[audio] play $file failed: $e'),
      ),
    );
  }

  static String _fileFor(Sfx sfx) {
    switch (sfx) {
      case Sfx.uiTap:
        return 'ui_tap.wav';
      case Sfx.correct:
        return 'correct.wav';
      case Sfx.target:
        return 'target.wav';
      case Sfx.invalid:
        return 'invalid.wav';
      case Sfx.fever:
        return 'fever.wav';
    }
  }

  @override
  void dispose() {}
}
